/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author neicua
 */
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import funzioni.*;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
    initComponents();
    // Scrivi questa riga qui sotto:
    jTable1.setFillsViewportHeight(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabellaDati = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SaveFile = new javax.swing.JButton();
        LoadFile = new javax.swing.JButton();
        SearchProduct = new javax.swing.JButton();
        BestPrice = new javax.swing.JButton();
        ShowAll = new javax.swing.JButton();
        SuppliersAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SuppliersRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", " ", "", "", "", "", ""
            }
        ));
        tabellaDati.setViewportView(jTable1);

        SaveFile.setText("Save file");
        SaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileActionPerformed(evt);
            }
        });

        LoadFile.setText("Load file");
        LoadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadFileActionPerformed(evt);
            }
        });

        SearchProduct.setBackground(new java.awt.Color(204, 255, 204));
        SearchProduct.setText("Search Product");
        SearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchProductActionPerformed(evt);
            }
        });

        BestPrice.setBackground(new java.awt.Color(204, 255, 204));
        BestPrice.setText("Product Best Price");
        BestPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestPriceActionPerformed(evt);
            }
        });

        ShowAll.setBackground(new java.awt.Color(204, 255, 204));
        ShowAll.setText("Reset Table");
        ShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowAllActionPerformed(evt);
            }
        });

        SuppliersAdd.setBackground(new java.awt.Color(204, 255, 204));
        SuppliersAdd.setText("Add Supplier");
        SuppliersAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppliersAddActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Price Comparisor");
        jLabel1.setAutoscrolls(true);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SuppliersRemove.setBackground(new java.awt.Color(204, 255, 204));
        SuppliersRemove.setText("Remove Supplier");
        SuppliersRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuppliersRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabellaDati)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoadFile)
                            .addComponent(SaveFile))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SearchProduct)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(BestPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(ShowAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(SuppliersAdd))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(38, 38, 38)
                        .addComponent(SuppliersRemove)
                        .addGap(91, 91, 91)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveFile))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BestPrice)
                    .addComponent(ShowAll)
                    .addComponent(SuppliersAdd)
                    .addComponent(SearchProduct)
                    .addComponent(LoadFile)
                    .addComponent(SuppliersRemove))
                .addGap(18, 18, 18)
                .addComponent(tabellaDati, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private GestoreFornitori gestore = new GestoreFornitori();
    private boolean fileCaricato = false;
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void SaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileActionPerformed
        
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Save file CSV");

        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV files (*.csv)", "csv");
        chooser.setFileFilter(filter);

        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {

            java.io.File file = chooser.getSelectedFile();

            // Aggiunge .csv se manca
            if (!file.getName().toLowerCase().endsWith(".csv")) {
                file = new java.io.File(file.getAbsolutePath() + ".csv");
            }

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {

                // Intestazioni colonne
                for (int i = 0; i < model.getColumnCount(); i++) {

                    bw.write(model.getColumnName(i));

                    if (i < model.getColumnCount() - 1) {
                        bw.write(";");
                    }
                }

                bw.newLine();

                // Dati tabella
                for (int r = 0; r < model.getRowCount(); r++) {

                    for (int c = 0; c < model.getColumnCount(); c++) {

                        Object valore = model.getValueAt(r, c);

                        bw.write(valore != null ? valore.toString() : "");

                        if (c < model.getColumnCount() - 1) {
                            bw.write(";");
                        }
                    }

                    bw.newLine();
                }

                JOptionPane.showMessageDialog(this,
                    "File saved successfully!");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this,
                    "Error while saving: " + e.getMessage());
            }
        }
        
    }//GEN-LAST:event_SaveFileActionPerformed

    private void LoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadFileActionPerformed
        fileCaricato = true;
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Load file CSV");
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {

            java.io.File file = chooser.getSelectedFile();

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            model.setRowCount(0);
            model.setColumnCount(0);

            gestore.svuota();

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {

                String linea;
                boolean primaRiga = true;

                while ((linea = br.readLine()) != null) {

                    String[] d = linea.split(";");

                    if (primaRiga) {
                        for (String col : d) model.addColumn(col);
                        primaRiga = false;
                    } else {

                        model.addRow(d);

                        Fornitori f = new Fornitori(
                            Integer.parseInt(d[0]),
                            d[1],
                            d[2],
                            d[3],
                            d[4],
                            d[5],
                            Double.parseDouble(d[6]),
                            Integer.parseInt(d[7]),
                            Integer.parseInt(d[8])
                        );

                        gestore.aggiungi(f);
                    }
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_LoadFileActionPerformed

    private void SearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchProductActionPerformed
    
    if (!fileCaricato) {
        JOptionPane.showMessageDialog(this,
            "you must load a file!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }

  
    String prodotto = JOptionPane.showInputDialog(this, "Inserisci prodotto:");

        if (prodotto == null) {
            return;
        }

        if (prodotto.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Enter a valid product!",
                "Atcention",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        ArrayList<Fornitori> lista = gestore.getByProdotto(prodotto);

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "No suppliers found for this product",
                "INFO",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (Fornitori f : lista) {
            model.addRow(new Object[]{
                f.getIdFornitore(),
                f.getRagioneSociale(),
                f.getPartitaIva(),
                f.getTelefono(),
                f.getEmail(),
                f.getProdotto(),
                f.getPrezzoUnitario(),
                f.getScontoPercentuale(),
                f.getTempoConsegnaGiorni()
            });
        }
    }//GEN-LAST:event_SearchProductActionPerformed

    private void BestPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestPriceActionPerformed
        if (!fileCaricato) {
            JOptionPane.showMessageDialog(this,
                "you must load a file!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        String prodotto = JOptionPane.showInputDialog(this, "Prodotto:");

        if (prodotto == null || prodotto.trim().isEmpty()) {
            return;
        }

        ArrayList<Fornitori> lista = gestore.migliorPrezzo(prodotto);

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "No supplier present!",
                "INFO",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (Fornitori f : lista) {

            model.addRow(new Object[]{
                f.getIdFornitore(),
                f.getRagioneSociale(),
                f.getPartitaIva(),
                f.getTelefono(),
                f.getEmail(),
                f.getProdotto(),
                f.getPrezzoUnitario(),
                f.getScontoPercentuale(),
                f.getTempoConsegnaGiorni()
            });
        }
    }//GEN-LAST:event_BestPriceActionPerformed

    private void ShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowAllActionPerformed
        if (!fileCaricato) {
            JOptionPane.showMessageDialog(this,
                "you must load a file!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (gestore.getFornitori().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "No supplier present!",
                "INFO",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (Fornitori f : gestore.getFornitori()) {

            model.addRow(new Object[]{
                f.getIdFornitore(),
                f.getRagioneSociale(),
                f.getPartitaIva(),
                f.getTelefono(),
                f.getEmail(),
                f.getProdotto(),
                f.getPrezzoUnitario(),
                f.getScontoPercentuale(),
                f.getTempoConsegnaGiorni()
            });
        }
    }//GEN-LAST:event_ShowAllActionPerformed

    private void SuppliersAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppliersAddActionPerformed
    if (!fileCaricato) {
        JOptionPane.showMessageDialog(this,
            "you must load a file!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
        
    try {


        String idStr = JOptionPane.showInputDialog(this, "ID Supplier:");
        if (idStr == null || idStr.trim().isEmpty()) return;

        int id = Integer.parseInt(idStr);

        for (Fornitori l : gestore.getFornitori()) {
            if (l.getIdFornitore() == id) {
                JOptionPane.showMessageDialog(this,
                    "ID already exists!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        String ragioneSociale = JOptionPane.showInputDialog(this, "Company name:");
        String partitaIva = JOptionPane.showInputDialog(this, "VAT number:");
        String telefono = JOptionPane.showInputDialog(this, "Phone number:");
        String email = JOptionPane.showInputDialog(this, "Email:");
        String prodotto = JOptionPane.showInputDialog(this, "Product:");
        String prezzoStr = JOptionPane.showInputDialog(this, "Unit price:");
        String scontoStr = JOptionPane.showInputDialog(this, "Discount (%):");
        String consegnaStr = JOptionPane.showInputDialog(this, "Delivery time (days):");

        if (idStr == null || ragioneSociale == null || partitaIva == null ||
            telefono == null || email == null || prodotto == null ||
            prezzoStr == null || scontoStr == null || consegnaStr == null) {
            return;
        }

        Fornitori f = new Fornitori(
            Integer.parseInt(idStr),
            ragioneSociale,
            partitaIva,
            telefono,
            email,
            prodotto,
            Double.parseDouble(prezzoStr),
            Integer.parseInt(scontoStr),
            Integer.parseInt(consegnaStr)
        );

        gestore.aggiungi(f);

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.addRow(new Object[]{
            f.getIdFornitore(),
            f.getRagioneSociale(),
            f.getPartitaIva(),
            f.getTelefono(),
            f.getEmail(),
            f.getProdotto(),
            f.getPrezzoUnitario(),
            f.getScontoPercentuale(),
            f.getTempoConsegnaGiorni()
        });

        JOptionPane.showMessageDialog(this, "Supplier added successfully!");

    } 
    catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
            "Please enter valid numeric values!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    catch (IllegalArgumentException e) {

        JOptionPane.showMessageDialog(this,
            e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    catch (Exception e) {

        JOptionPane.showMessageDialog(this,
            "Generic error!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_SuppliersAddActionPerformed

    private void SuppliersRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuppliersRemoveActionPerformed
        if (!fileCaricato) {
            JOptionPane.showMessageDialog(this,
                "you must load a file!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {

            String idStr = JOptionPane.showInputDialog(this, "Enter Supplier ID to delete:");

            if (idStr == null || idStr.trim().isEmpty()) return;

            int id = Integer.parseInt(idStr);

            Fornitori daEliminare = null;

            for (Fornitori f : gestore.getFornitori()) {

                if (f.getIdFornitore() == id) {
                    daEliminare = f;
                    break;
                }
            }

            if (daEliminare == null) {
                JOptionPane.showMessageDialog(this,
                    "Supplier not found!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            int conferma = JOptionPane.showConfirmDialog(this,
                "Do you want to delete the supplier with ID " + id + "?",
                "Confirm deletion",
                JOptionPane.YES_NO_OPTION);

            if (conferma != JOptionPane.YES_OPTION) {
                return;
            }

            gestore.getFornitori().remove(daEliminare);

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            model.setRowCount(0);

            for (Fornitori f : gestore.getFornitori()) {

                model.addRow(new Object[]{
                    f.getIdFornitore(),
                    f.getRagioneSociale(),
                    f.getPartitaIva(),
                    f.getTelefono(),
                    f.getEmail(),
                    f.getProdotto(),
                    f.getPrezzoUnitario(),
                    f.getScontoPercentuale(),
                    f.getTempoConsegnaGiorni()
                });
            }
            JOptionPane.showMessageDialog(this,
                "Supplier successfully deleted!");

        } 
        catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                "Please enter valid numeric values!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        catch (IllegalArgumentException e) {

            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                "Generic error!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SuppliersRemoveActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
        new MainGUI().setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BestPrice;
    private javax.swing.JButton LoadFile;
    private javax.swing.JButton SaveFile;
    private javax.swing.JButton SearchProduct;
    private javax.swing.JButton ShowAll;
    private javax.swing.JButton SuppliersAdd;
    private javax.swing.JButton SuppliersRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tabellaDati;
    // End of variables declaration//GEN-END:variables
}
